site_name: 'tgl Documentation'
site_description: 'Independent command-line client and Python library for Toggl Track'
site_author: 'Sebastian Kwon'

copyright: 'Copyright &copy; 2026 Sebastian Kwon'

repo_name: 'sekR4/tgl'
repo_url: 'https://github.com/sekR4/tgl'
theme:
  name: 'material'
  palette:
    primary: 'amber'
    accent: 'amber'
  icon:
    logo: 'material/power'
    repo: fontawesome/brands/git-alt

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

nav:
  - About: 'index.md'
  - Command Line Interface: 'cli.md'
  - API Wrappers: 'api.md'
