name: Publish to PyPi

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'
gs
      - name: Install requirements
        run: |
          pip install --upgrade --upgrade-strategy eager -r test-requirements.txt -e .

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Publish documentation
        run: mkdocs gh-deploy --force
