name: Release

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: python
          package-name: togglCli

  publish:
    runs-on: ubuntu-latest
    needs: release-please
    if: needs.release-please.outputs.release_created == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # We need the whole Git history in order for the PBR to pick up correctly the tag

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Install requirements
        run: |
          pip install --upgrade --upgrade-strategy eager -r test-requirements.txt -e .

      - name: Build distribution 📦
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Publish documentation
        run: mkdocs gh-deploy --force
